"""create decision_recommendations table

Revision ID: d16b39e69f23
Revises: 637b08631504
Create Date: 2026-10-03 19:42:28.897996+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd16b39e69f23'
down_revision: Union[str, None] = '637b08631504'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('forecast_horizon_days', sa.Integer(), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('current_available_stock', sa.Integer(), nullable=False),
    sa.Column('reorder_point', sa.Integer(), nullable=False),
    sa.Column('predicted_demand', sa.Float(), nullable=False),
    sa.Column('lead_time_demand', sa.Float(), nullable=False),
    sa.Column('stockout_risk_level', sa.String(length=50), nullable=False),
    sa.Column('replenishment_required', sa.Boolean(), nullable=False),
    sa.Column('recommended_order_quantity', sa.Integer(), nullable=False),
    sa.Column('selected_supplier_id', sa.Integer(), nullable=True),
    sa.Column('selected_supplier_name', sa.String(length=200), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('estimated_total_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('factors', sa.JSON(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('policy_references', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('approval_status', sa.String(length=50), server_default='PENDING', nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('source_agent_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['selected_supplier_id'], ['suppliers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_recommendations_approval_status'), 'decision_recommendations', ['approval_status'], unique=False)
    op.create_index(op.f('ix_decision_recommendations_id'), 'decision_recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_decision_recommendations_product_id'), 'decision_recommendations', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decision_recommendations_product_id'), table_name='decision_recommendations')
    op.drop_index(op.f('ix_decision_recommendations_id'), table_name='decision_recommendations')
    op.drop_index(op.f('ix_decision_recommendations_approval_status'), table_name='decision_recommendations')
    op.drop_table('decision_recommendations')
    # ### end Alembic commands ###
